In [17]:
import pandas as pd
import numpy as np
import seaborn as sn
import matplotlib.pyplot as plt

actualDatasetFull = pd.read_excel('CHEVRON_ACTUAL.xlsx')
targetDatasetFull = pd.read_excel('CHEVRON_TARGET.xlsx')

In [18]:
uniqueCombinations = targetDatasetFull.drop_duplicates(subset=['Stock Family', 'Stock Category New', 'Stock Category','Stock Sub Category','New Inventory Date','Plant Name'])

# Compare lengths
if len(targetDatasetFull) == len(uniqueCombinations):
    print("All records are unique based on the combination of the three columns.")
else:
    print("There are duplicate records based on the combination of the three columns.")
print(len(targetDatasetFull) , len(uniqueCombinations))

There are duplicate records based on the combination of the three columns.
34905 34827

In [19]:
duplicates = targetDatasetFull[['Stock Family', 'Stock Category New', 'Stock Category','Stock Sub Category','New Inventory Date','Plant Name']][targetDatasetFull[['Stock Family', 'Stock Category New', 'Stock Category','Stock Sub Category','New Inventory Date','Plant Name']].duplicated()]
duplicates

,Stock Family,Stock Category New,Stock Category,Stock Sub Category,New Inventory Date,Plant Name
1430,PRODUCTS,DISTILLATE,JET,JET,2021-06-30,EL DORADO BOGOTA AIR BOG
1504,PRODUCTS,DISTILLATE,JET,JET,2021-06-30,PUENTE ARANDA BOGOTA TRM
2310,PRODUCTS,DISTILLATE,JET,JET,2021-07-31,EL DORADO BOGOTA AIR BOG
2384,PRODUCTS,DISTILLATE,JET,JET,2021-07-31,PUENTE ARANDA BOGOTA TRM
3175,PRODUCTS,DISTILLATE,JET,JET,2021-08-31,EL DORADO BOGOTA AIR BOG
...,...,...,...,...,...,...
32838,PRODUCTS,DISTILLATE,JET,JET,2024-06-30,PUENTE ARANDA BOGOTA TRM
33630,PRODUCTS,DISTILLATE,JET,JET,2024-07-31,EL DORADO BOGOTA AIR BOG
33703,PRODUCTS,DISTILLATE,JET,JET,2024-07-31,PUENTE ARANDA BOGOTA TRM
34496,PRODUCTS,DISTILLATE,JET,JET,2024-08-31,EL DORADO BOGOTA AIR BOG
34569,PRODUCTS,DISTILLATE,JET,JET,2024-08-31,PUENTE ARANDA BOGOTA TRM

In [23]:
duplicates = actualDatasetFull[['Stock Family', 'Stock Category New', 'Stock Category','Stock Sub Category','New Inventory Date','Plant Name']][actualDatasetFull[['Stock Family', 'Stock Category New', 'Stock Category','Stock Sub Category','New Inventory Date','Plant Name']].duplicated()]
duplicates

,Stock Family,Stock Category New,Stock Category,Stock Sub Category,New Inventory Date,Plant Name
107,CRUDE,CRUDE,CRUDE,CRUDE,2021-06-30,EL SEGUNDO CA RFY CHEVRON
109,CRUDE,CRUDE,CRUDE,CRUDE,2021-06-30,RICHMOND CA RFY CHEVRON
113,CRUDE,CRUDE,CRUDE,CRUDE,2021-07-31,EL SEGUNDO CA RFY CHEVRON
116,CRUDE,CRUDE,CRUDE,CRUDE,2021-07-31,RICHMOND CA RFY CHEVRON
120,CRUDE,CRUDE,CRUDE,CRUDE,2021-08-31,EL SEGUNDO CA RFY CHEVRON
...,...,...,...,...,...,...
38546,OTHER,OTHER,LPG,LPG,2021-06-30,PASCAGOULA MS RFY CHEVRON
38547,OTHER,OTHER,LPG,LPG,2021-06-30,PASCAGOULA MS RFY CHEVRON
38548,OTHER,OTHER,LPG,LPG,2021-06-30,PASCAGOULA MS RFY CHEVRON
38549,OTHER,OTHER,LPG,LPG,2021-06-30,PASCAGOULA MS RFY CHEVRON
38553,PRODUCTS,DISTILLATE,LSD,LSD,2021-06-30,PASCAGOULA MS RFY CHEVRON

In [22]:
actualDatasetFull = actualDatasetFull.dropna(subset = ['Plant Name'])

In [24]:
groupedActual = actualDatasetFull.groupby(['Stock Family', 'Stock Category New', 'Stock Category','Stock Sub Category','New Inventory Date','Plant Name','Item Type','Transit Type','Terminal Type','Refinery Area Desc','PW Source System','Refinery Area','Plant Status'])[['Volume BBL','Volume MBD','Book Volume BBL','Book Volume MBD']].sum().reset_index()groupedActual

In [25]:
duplicates = groupedActual[['Stock Family', 'Stock Category New', 'Stock Category','Stock Sub Category','New Inventory Date','Plant Name']][groupedActual[['Stock Family', 'Stock Category New', 'Stock Category','Stock Sub Category','New Inventory Date','Plant Name']].duplicated()]
duplicates

Empty DataFrame
Columns: [Stock Family, Stock Category New, Stock Category, Stock Sub Category, New Inventory Date, Plant Name]
Index: []

In [26]:
groupedTarget = targetDatasetFull.groupby(['Stock Family', 'Stock Category New', 'Stock Category','Stock Sub Category','New Inventory Date','Plant Name','Target Type','PW Location Code','PW Location Level 0','PW Location Level 1','PW Location Level 2','PW Location Level 3'])[['Volume BBL','Volume MBD','Book Volume BBL','Book Volume MBD']].sum().reset_index()

In [27]:
duplicates = groupedTarget[['Stock Family', 'Stock Category New', 'Stock Category','Stock Sub Category','New Inventory Date','Plant Name']][groupedTarget[['Stock Family', 'Stock Category New', 'Stock Category','Stock Sub Category','New Inventory Date','Plant Name']].duplicated()]
duplicates

Empty DataFrame
Columns: [Stock Family, Stock Category New, Stock Category, Stock Sub Category, New Inventory Date, Plant Name]
Index: []

In [28]:
groupedActual = groupedActual.rename(columns={'Volume BBL':'Volume_BBL_Actual','Volume MBD':'Volume_MBD_Actual','Book Volume BBL':'Book_Volume_BBL_Actual','Book Volume MBD':'Book_Volume_MBD_Actual'})
groupedActual

,Stock Family,Stock Category New,Stock Category,Stock Sub Category,New Inventory Date,Plant Name,Item Type,Transit Type,Terminal Type,Refinery Area Desc,PW Source System,Refinery Area,Plant Status,Volume_BBL_Actual,Volume_MBD_Actual,Book_Volume_BBL_Actual,Book_Volume_MBD_Actual
0,CRUDE,CRUDE,CRUDE,CRUDE,2021-06-30,EL SEGUNDO CA RFY CHEVRON,BookInventory,InTank,Refinery,El Segundo,PW1,ELSE,Active,2162744.31,2162.75,2162744.31,2162.75
1,CRUDE,CRUDE,CRUDE,CRUDE,2021-06-30,PASADENA TX RFY CHEVRON,BookInventory,InTank,Refinery,Pasadena,PW2,PASA,Active,1325873.58,1325.86,1325873.58,1325.86
2,CRUDE,CRUDE,CRUDE,CRUDE,2021-06-30,PASCAGOULA MS RFY CHEVRON,BookInventory,InTank,Refinery,Pascagoula,PW2,PASC,Active,1919979.20,1920.00,1919979.20,1920.00
3,CRUDE,CRUDE,CRUDE,CRUDE,2021-06-30,RICHMOND CA RFY CHEVRON,BookInventory,InTank,Refinery,Richmond,PW1,RICH,Active,2162689.50,2162.69,2162689.50,2162.69
4,CRUDE,CRUDE,CRUDE,CRUDE,2021-06-30,SALT LAKE CITY UT RFY CHEVRON,BookInventory,InTank,Refinery,Salt Lake,PW6,SLAK,Active,322848.00,322.85,322848.00,322.85
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27633,PRODUCTS,GASOLINE,MOGAS,RUL,2024-04-30,WASKOM TX TRM SUNOCO,BookInventory,InTank,Terminal,Pascagoula,PW2,PASC,Active,4445.50,4.45,4445.50,4.45
27634,PRODUCTS,GASOLINE,MOGAS,RUL,2024-04-30,WATSON PPL CA INTRANSIT,BookInventory,InTransit,InTransit,El Segundo,PW1,ELSE,Active,27663.60,27.66,27663.60,27.66
27635,PRODUCTS,GASOLINE,MOGAS,RUL,2024-04-30,WILLIAMS PPL OK INTRANSIT,BookInventory,InTransit,InTransit,Pascagoula,PW2,PASC,Active,2035.00,2.04,2035.00,2.04
27636,PRODUCTS,GASOLINE,MOGAS,RUL,2024-04-30,YUMBO - BUENAVENTURA PPL,BookInventory,InTransit,InTransit,CCA,PW2,CO00,Active,11723.05,11.72,11723.05,11.72
27637,PRODUCTS,GASOLINE,MOGAS,RUL,2024-04-30,YUMBO TRM,BookInventory,InTank,Terminal,CCA,PW2,CO00,Active,4458.35,4.46,4458.35,4.46

In [29]:
groupedTarget = groupedTarget.rename(columns={'Volume BBL':'Volume_BBL_Target','Volume MBD':'Volume_MBD_Target','Book Volume BBL':'Book_Volume_BBL_Target','Book Volume MBD':'Book_Volume_MBD_Target'})
groupedTarget

,Stock Family,Stock Category New,Stock Category,Stock Sub Category,New Inventory Date,Plant Name,Target Type,PW Location Code,PW Location Level 0,PW Location Level 1,PW Location Level 2,PW Location Level 3,Volume_BBL_Target,Volume_MBD_Target,Book_Volume_BBL_Target,Book_Volume_MBD_Target
0,CRUDE,CRUDE,CRUDE,CRUDE,2021-06-30,EL SEGUNDO CA RFY CHEVRON,Defined,EL SEGUNDO,US WEST COAST,EL SEGUNDO SUPPLY AREA,EL SEGUNDO REFINERY,EL SEGUNDO,2345000.00,2345.00,2345000.00,2345.00
1,CRUDE,CRUDE,CRUDE,CRUDE,2021-06-30,MISSISSIPPI MS MAR INTRANSIT,Calculated,PASCAGOULA,US EAST,PASCAGOULA SUPPLY AREA,PASCAGOULA REFINERY,PASCAGOULA,78818.58,78.82,78818.58,78.82
2,CRUDE,CRUDE,CRUDE,CRUDE,2021-06-30,PASADENA TX RFY CHEVRON,Defined,PASADENA,US EAST,PASADENA SUPPLY AREA,PASADENA REFINERY,PASADENA,745000.00,745.00,745000.00,745.00
3,CRUDE,CRUDE,CRUDE,CRUDE,2021-06-30,PASCAGOULA MS RFY CHEVRON,Defined,PASCAGOULA,US EAST,PASCAGOULA SUPPLY AREA,PASCAGOULA REFINERY,PASCAGOULA,2186000.00,2186.00,2186000.00,2186.00
4,CRUDE,CRUDE,CRUDE,CRUDE,2021-06-30,RICHMOND CA RFY CHEVRON,Defined,RICHMOND,US WEST COAST,RICHMOND SUPPLY AREA,RICHMOND REFINERY,RICHMOND,1780000.00,1780.00,1780000.00,1780.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34822,PRODUCTS,GASOLINE,MOGAS,RUL,2024-08-31,WASKOM TX TRM SUNOCO,Calculated,TEXAS,US EAST,PASADENA SUPPLY AREA,TEXAS,TEXAS,4225.59,4.23,4225.59,4.23
34823,PRODUCTS,GASOLINE,MOGAS,RUL,2024-08-31,WATSON PPL CA INTRANSIT,Calculated,KM SOCAL,US WEST COAST,EL SEGUNDO SUPPLY AREA,SOCAL AREA,KM SOCAL,107850.40,107.85,107850.40,107.85
34824,PRODUCTS,GASOLINE,MOGAS,RUL,2024-08-31,WILLIAMS PPL OK INTRANSIT,Calculated,TEXAS,US EAST,PASADENA SUPPLY AREA,TEXAS,TEXAS,2202.82,2.20,2202.82,2.20
34825,PRODUCTS,GASOLINE,MOGAS,RUL,2024-08-31,YUMBO - BUENAVENTURA PPL,Calculated,COLOMBIA,US EAST,LATAM SYSTEM,COLOMBIA,COLOMBIA,8478.67,8.48,8478.67,8.48
34826,PRODUCTS,GASOLINE,MOGAS,RUL,2024-08-31,YUMBO TRM,Calculated,COLOMBIA,US EAST,LATAM SYSTEM,COLOMBIA,COLOMBIA,10793.30,10.79,10793.30,10.79

In [47]:
merged_df = pd.merge(groupedTarget, groupedActual , on=['Stock Family', 'Stock Category New', 'Stock Category','Stock Sub Category','New Inventory Date','Plant Name'])
pd.set_option('display.max_columns', None)
merged_df

,Stock Family,Stock Category New,Stock Category,Stock Sub Category,New Inventory Date,Plant Name,Target Type,PW Location Code,PW Location Level 0,PW Location Level 1,PW Location Level 2,PW Location Level 3,Volume_BBL_Target,Volume_MBD_Target,Book_Volume_BBL_Target,Book_Volume_MBD_Target,Item Type,Transit Type,Terminal Type,Refinery Area Desc,PW Source System,Refinery Area,Plant Status,Volume_BBL_Actual,Volume_MBD_Actual,Book_Volume_BBL_Actual,Book_Volume_MBD_Actual
0,CRUDE,CRUDE,CRUDE,CRUDE,2021-06-30,EL SEGUNDO CA RFY CHEVRON,Defined,EL SEGUNDO,US WEST COAST,EL SEGUNDO SUPPLY AREA,EL SEGUNDO REFINERY,EL SEGUNDO,2345000.00,2345.00,2345000.00,2345.00,BookInventory,InTank,Refinery,El Segundo,PW1,ELSE,Active,2162744.31,2162.75,2162744.31,2162.75
1,CRUDE,CRUDE,CRUDE,CRUDE,2021-06-30,PASADENA TX RFY CHEVRON,Defined,PASADENA,US EAST,PASADENA SUPPLY AREA,PASADENA REFINERY,PASADENA,745000.00,745.00,745000.00,745.00,BookInventory,InTank,Refinery,Pasadena,PW2,PASA,Active,1325873.58,1325.86,1325873.58,1325.86
2,CRUDE,CRUDE,CRUDE,CRUDE,2021-06-30,PASCAGOULA MS RFY CHEVRON,Defined,PASCAGOULA,US EAST,PASCAGOULA SUPPLY AREA,PASCAGOULA REFINERY,PASCAGOULA,2186000.00,2186.00,2186000.00,2186.00,BookInventory,InTank,Refinery,Pascagoula,PW2,PASC,Active,1919979.20,1920.00,1919979.20,1920.00
3,CRUDE,CRUDE,CRUDE,CRUDE,2021-06-30,RICHMOND CA RFY CHEVRON,Defined,RICHMOND,US WEST COAST,RICHMOND SUPPLY AREA,RICHMOND REFINERY,RICHMOND,1780000.00,1780.00,1780000.00,1780.00,BookInventory,InTank,Refinery,Richmond,PW1,RICH,Active,2162689.50,2162.69,2162689.50,2162.69
4,CRUDE,CRUDE,CRUDE,CRUDE,2021-06-30,SALT LAKE CITY UT RFY CHEVRON,Defined,SALT LAKE REFINERY,SALT LAKE OPT AREA,SALT LAKE REFINERY,SALT LAKE REFINERY,SALT LAKE REFINERY,260000.00,260.00,260000.00,260.00,BookInventory,InTank,Refinery,Salt Lake,PW6,SLAK,Active,322848.00,322.85,322848.00,322.85
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26963,PRODUCTS,GASOLINE,MOGAS,RUL,2024-04-30,WASKOM TX TRM SUNOCO,Calculated,TEXAS,US EAST,PASADENA SUPPLY AREA,TEXAS,TEXAS,4225.59,4.23,4225.59,4.23,BookInventory,InTank,Terminal,Pascagoula,PW2,PASC,Active,4445.50,4.45,4445.50,4.45
26964,PRODUCTS,GASOLINE,MOGAS,RUL,2024-04-30,WATSON PPL CA INTRANSIT,Calculated,KM SOCAL,US WEST COAST,EL SEGUNDO SUPPLY AREA,SOCAL AREA,KM SOCAL,107850.40,107.85,107850.40,107.85,BookInventory,InTransit,InTransit,El Segundo,PW1,ELSE,Active,27663.60,27.66,27663.60,27.66
26965,PRODUCTS,GASOLINE,MOGAS,RUL,2024-04-30,WILLIAMS PPL OK INTRANSIT,Calculated,TEXAS,US EAST,PASADENA SUPPLY AREA,TEXAS,TEXAS,2202.82,2.20,2202.82,2.20,BookInventory,InTransit,InTransit,Pascagoula,PW2,PASC,Active,2035.00,2.04,2035.00,2.04
26966,PRODUCTS,GASOLINE,MOGAS,RUL,2024-04-30,YUMBO - BUENAVENTURA PPL,Calculated,COLOMBIA,US EAST,LATAM SYSTEM,COLOMBIA,COLOMBIA,8478.67,8.48,8478.67,8.48,BookInventory,InTransit,InTransit,CCA,PW2,CO00,Active,11723.05,11.72,11723.05,11.72
26967,PRODUCTS,GASOLINE,MOGAS,RUL,2024-04-30,YUMBO TRM,Calculated,COLOMBIA,US EAST,LATAM SYSTEM,COLOMBIA,COLOMBIA,10793.30,10.79,10793.30,10.79,BookInventory,InTank,Terminal,CCA,PW2,CO00,Active,4458.35,4.46,4458.35,4.46

In [48]:
# Check for missing values
missing_values = merged_df.isnull()
#print(missing_values)

# Count missing values in each column
missing_count = merged_df.isnull().sum()
print(missing_count)

Stock Family              0
Stock Category New        0
Stock Category            0
Stock Sub Category        0
New Inventory Date        0
Plant Name                0
Target Type               0
PW Location Code          0
PW Location Level 0       0
PW Location Level 1       0
PW Location Level 2       0
PW Location Level 3       0
Volume_BBL_Target         0
Volume_MBD_Target         0
Book_Volume_BBL_Target    0
Book_Volume_MBD_Target    0
Item Type                 0
Transit Type              0
Terminal Type             0
Refinery Area Desc        0
PW Source System          0
Refinery Area             0
Plant Status              0
Volume_BBL_Actual         0
Volume_MBD_Actual         0
Book_Volume_BBL_Actual    0
Book_Volume_MBD_Actual    0
dtype: int64

In [49]:
unique_values = merged_df.nunique()
print(unique_values)

Stock Family                  4
Stock Category New            9
Stock Category               42
Stock Sub Category           45
New Inventory Date           35
Plant Name                  234
Target Type                   2
PW Location Code             49
PW Location Level 0           3
PW Location Level 1          10
PW Location Level 2          33
PW Location Level 3          49
Volume_BBL_Target           855
Volume_MBD_Target           620
Book_Volume_BBL_Target      855
Book_Volume_MBD_Target      620
Item Type                     1
Transit Type                  2
Terminal Type                 3
Refinery Area Desc            6
PW Source System              3
Refinery Area                13
Plant Status                  1
Volume_BBL_Actual         24275
Volume_MBD_Actual          9074
Book_Volume_BBL_Actual    24275
Book_Volume_MBD_Actual     9074
dtype: int64

In [50]:
final_dataset = merged_df

In [51]:
final_dataset['New Inventory Date'] = pd.to_datetime(final_dataset['New Inventory Date'])

# Extract year and month
final_dataset['Year'] = final_dataset['New Inventory Date'].dt.year
final_dataset['Month'] = final_dataset['New Inventory Date'].dt.strftime('%b')
final_dataset['Variance'] = ((final_dataset['Volume_MBD_Target']-final_dataset['Volume_MBD_Actual'])/final_dataset['Volume_MBD_Target'])*100

In [52]:
final_dataset

,Stock Family,Stock Category New,Stock Category,Stock Sub Category,New Inventory Date,Plant Name,Target Type,PW Location Code,PW Location Level 0,PW Location Level 1,PW Location Level 2,PW Location Level 3,Volume_BBL_Target,Volume_MBD_Target,Book_Volume_BBL_Target,Book_Volume_MBD_Target,Item Type,Transit Type,Terminal Type,Refinery Area Desc,PW Source System,Refinery Area,Plant Status,Volume_BBL_Actual,Volume_MBD_Actual,Book_Volume_BBL_Actual,Book_Volume_MBD_Actual,Year,Month,Variance
0,CRUDE,CRUDE,CRUDE,CRUDE,2021-06-30,EL SEGUNDO CA RFY CHEVRON,Defined,EL SEGUNDO,US WEST COAST,EL SEGUNDO SUPPLY AREA,EL SEGUNDO REFINERY,EL SEGUNDO,2345000.00,2345.00,2345000.00,2345.00,BookInventory,InTank,Refinery,El Segundo,PW1,ELSE,Active,2162744.31,2162.75,2162744.31,2162.75,2021,Jun,7.771855
1,CRUDE,CRUDE,CRUDE,CRUDE,2021-06-30,PASADENA TX RFY CHEVRON,Defined,PASADENA,US EAST,PASADENA SUPPLY AREA,PASADENA REFINERY,PASADENA,745000.00,745.00,745000.00,745.00,BookInventory,InTank,Refinery,Pasadena,PW2,PASA,Active,1325873.58,1325.86,1325873.58,1325.86,2021,Jun,-77.967785
2,CRUDE,CRUDE,CRUDE,CRUDE,2021-06-30,PASCAGOULA MS RFY CHEVRON,Defined,PASCAGOULA,US EAST,PASCAGOULA SUPPLY AREA,PASCAGOULA REFINERY,PASCAGOULA,2186000.00,2186.00,2186000.00,2186.00,BookInventory,InTank,Refinery,Pascagoula,PW2,PASC,Active,1919979.20,1920.00,1919979.20,1920.00,2021,Jun,12.168344
3,CRUDE,CRUDE,CRUDE,CRUDE,2021-06-30,RICHMOND CA RFY CHEVRON,Defined,RICHMOND,US WEST COAST,RICHMOND SUPPLY AREA,RICHMOND REFINERY,RICHMOND,1780000.00,1780.00,1780000.00,1780.00,BookInventory,InTank,Refinery,Richmond,PW1,RICH,Active,2162689.50,2162.69,2162689.50,2162.69,2021,Jun,-21.499438
4,CRUDE,CRUDE,CRUDE,CRUDE,2021-06-30,SALT LAKE CITY UT RFY CHEVRON,Defined,SALT LAKE REFINERY,SALT LAKE OPT AREA,SALT LAKE REFINERY,SALT LAKE REFINERY,SALT LAKE REFINERY,260000.00,260.00,260000.00,260.00,BookInventory,InTank,Refinery,Salt Lake,PW6,SLAK,Active,322848.00,322.85,322848.00,322.85,2021,Jun,-24.173077
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26963,PRODUCTS,GASOLINE,MOGAS,RUL,2024-04-30,WASKOM TX TRM SUNOCO,Calculated,TEXAS,US EAST,PASADENA SUPPLY AREA,TEXAS,TEXAS,4225.59,4.23,4225.59,4.23,BookInventory,InTank,Terminal,Pascagoula,PW2,PASC,Active,4445.50,4.45,4445.50,4.45,2024,Apr,-5.200946
26964,PRODUCTS,GASOLINE,MOGAS,RUL,2024-04-30,WATSON PPL CA INTRANSIT,Calculated,KM SOCAL,US WEST COAST,EL SEGUNDO SUPPLY AREA,SOCAL AREA,KM SOCAL,107850.40,107.85,107850.40,107.85,BookInventory,InTransit,InTransit,El Segundo,PW1,ELSE,Active,27663.60,27.66,27663.60,27.66,2024,Apr,74.353268
26965,PRODUCTS,GASOLINE,MOGAS,RUL,2024-04-30,WILLIAMS PPL OK INTRANSIT,Calculated,TEXAS,US EAST,PASADENA SUPPLY AREA,TEXAS,TEXAS,2202.82,2.20,2202.82,2.20,BookInventory,InTransit,InTransit,Pascagoula,PW2,PASC,Active,2035.00,2.04,2035.00,2.04,2024,Apr,7.272727
26966,PRODUCTS,GASOLINE,MOGAS,RUL,2024-04-30,YUMBO - BUENAVENTURA PPL,Calculated,COLOMBIA,US EAST,LATAM SYSTEM,COLOMBIA,COLOMBIA,8478.67,8.48,8478.67,8.48,BookInventory,InTransit,InTransit,CCA,PW2,CO00,Active,11723.05,11.72,11723.05,11.72,2024,Apr,-38.207547
26967,PRODUCTS,GASOLINE,MOGAS,RUL,2024-04-30,YUMBO TRM,Calculated,COLOMBIA,US EAST,LATAM SYSTEM,COLOMBIA,COLOMBIA,10793.30,10.79,10793.30,10.79,BookInventory,InTank,Terminal,CCA,PW2,CO00,Active,4458.35,4.46,4458.35,4.46,2024,Apr,58.665431

In [53]:
final_dataset.drop(['Item Type','Plant Status','Plant Name','New Inventory Date','PW Location Level 3','PW Location Level 2','PW Location Code','Stock Sub Category','Book_Volume_BBL_Target','Book_Volume_MBD_Target','Book_Volume_BBL_Actual','Book_Volume_MBD_Actual','Volume_BBL_Target','Volume_BBL_Actual'],axis=1, inplace=True)

In [54]:
unique_values = final_dataset.nunique()
print(unique_values)

Stock Family               4
Stock Category New         9
Stock Category            42
Target Type                2
PW Location Level 0        3
PW Location Level 1       10
Volume_MBD_Target        620
Transit Type               2
Terminal Type              3
Refinery Area Desc         6
PW Source System           3
Refinery Area             13
Volume_MBD_Actual       9074
Year                       4
Month                     12
Variance               19233
dtype: int64

In [56]:
final_dataset

,Stock Family,Stock Category New,Stock Category,Target Type,PW Location Level 0,PW Location Level 1,Volume_MBD_Target,Transit Type,Terminal Type,Refinery Area Desc,PW Source System,Refinery Area,Volume_MBD_Actual,Year,Month,Variance
0,CRUDE,CRUDE,CRUDE,Defined,US WEST COAST,EL SEGUNDO SUPPLY AREA,2345.00,InTank,Refinery,El Segundo,PW1,ELSE,2162.75,2021,Jun,7.771855
1,CRUDE,CRUDE,CRUDE,Defined,US EAST,PASADENA SUPPLY AREA,745.00,InTank,Refinery,Pasadena,PW2,PASA,1325.86,2021,Jun,-77.967785
2,CRUDE,CRUDE,CRUDE,Defined,US EAST,PASCAGOULA SUPPLY AREA,2186.00,InTank,Refinery,Pascagoula,PW2,PASC,1920.00,2021,Jun,12.168344
3,CRUDE,CRUDE,CRUDE,Defined,US WEST COAST,RICHMOND SUPPLY AREA,1780.00,InTank,Refinery,Richmond,PW1,RICH,2162.69,2021,Jun,-21.499438
4,CRUDE,CRUDE,CRUDE,Defined,SALT LAKE OPT AREA,SALT LAKE REFINERY,260.00,InTank,Refinery,Salt Lake,PW6,SLAK,322.85,2021,Jun,-24.173077
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26963,PRODUCTS,GASOLINE,MOGAS,Calculated,US EAST,PASADENA SUPPLY AREA,4.23,InTank,Terminal,Pascagoula,PW2,PASC,4.45,2024,Apr,-5.200946
26964,PRODUCTS,GASOLINE,MOGAS,Calculated,US WEST COAST,EL SEGUNDO SUPPLY AREA,107.85,InTransit,InTransit,El Segundo,PW1,ELSE,27.66,2024,Apr,74.353268
26965,PRODUCTS,GASOLINE,MOGAS,Calculated,US EAST,PASADENA SUPPLY AREA,2.20,InTransit,InTransit,Pascagoula,PW2,PASC,2.04,2024,Apr,7.272727
26966,PRODUCTS,GASOLINE,MOGAS,Calculated,US EAST,LATAM SYSTEM,8.48,InTransit,InTransit,CCA,PW2,CO00,11.72,2024,Apr,-38.207547
26967,PRODUCTS,GASOLINE,MOGAS,Calculated,US EAST,LATAM SYSTEM,10.79,InTank,Terminal,CCA,PW2,CO00,4.46,2024,Apr,58.665431

In [55]:
final_dataset.to_excel('final_dataset.xlsx')